name: dahlen-studio
recipe: lamp
config:
    php: '7.4'
    webroot: ./public_html
    database: mysql:5.7
    xdebug: true
    ssl: true
    build:
        - composer install
services:
    database:
        creds:
            database: elpadi_ds_pw
    phpmyadmin:
        type: phpmyadmin
        hosts:
          - database
