<?php
namespace ProcessWire;

use Functional as F;
use Thunder\Shortcode\HandlerContainer\HandlerContainer;
use Thunder\Shortcode\Parser\RegularParser;
use Thunder\Shortcode\Processor\Processor;
use Thunder\Shortcode\Shortcode\ShortcodeInterface;

/**
 * ProcessWire 'Hello world' demonstration module
 *
 * Demonstrates the Module interface and how to add hooks.
 * 
 * See README file for further links regarding module development.
 * 
 * This file is licensed under the MIT license
 * https://processwire.com/about/license/mit/
 * 
 * ProcessWire 3.x (development), Copyright 2015 by Ryan Cramer
 * https://processwire.com
 *
 */

class Zenphoto extends WireData implements Module {

	private static $zdb;

	const DEFAULT_MOTION_TIMING = 250;
	const DEFAULT_MOTION_START = 50;

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			// The module'ss title, typically a little more descriptive than the class name
			'title' => 'Zenphoto', 

			// version number 
			'version' => 1, 

			// summary is brief description of what this module is
			'summary' => 'Bridge between the data inside Zenphoto and ProcessWire.',
			
			// Optional URL to more information about the module
			'href' => '',

			// singular=true: indicates that only one instance of the module is allowed.
			// This is usually what you want for modules that attach hooks. 
			'singular' => true, 

			// autoload=true: indicates the module should be started with ProcessWire.
			// This is necessary for any modules that attach runtime hooks, otherwise those
			// hooks won't get attached unless some other code calls the module on it's own.
			// Note that autoload modules are almost always also 'singular' (seen above).
			'autoload' => true, 
		
			// Optional font-awesome icon name, minus the 'fa-' part
			'icon' => 'smile-o', 
			);
	}

	/**
	 * Initialize the module
	 *
	 * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
	 * when ProcessWire's API is ready. As a result, this is a good place to attach hooks. 
	 *
	 */
	public function init() {

		$this->addHook('Page::slideshowImages', $this, 'slideshowImages'); 
		$this->addHookAfter('Fieldtype::wakeupValue', $this, 'parseFieldShortcodes'); 

	}

	public function parseFieldShortcodes($event) {
		$page = $event->arguments[0];
		$field = $event->arguments[1];
		$value = $event->arguments[2];
		
		// don't add this to the admin pages
		if (!$GLOBALS['wire']->page || $GLOBALS['wire']->page->template->name === 'admin') return;

		// only run on content field
		if ($field->name !== 'content') return;

		$event->return = static::parseShortcodes($value);
	}

	public static function parseShortcodes($s) {
		$handlers = new HandlerContainer();
		foreach (['slideshow','motion','video'] as $method) $handlers->add($method, [__CLASS__, $method]);
		$processor = new Processor(new RegularParser(), $handlers);

		return $processor->withRecursionDepth(0)->process($s);
	}

	public function slideshowImages($event) {
		$page = $event->object;
		$event->return = static::fetchAlbumImages($page->name);
	}

	private static function zenphotoDB() {
		global $wire, $_zp_conf_vars;
		if (self::$zdb) return self::$zdb;
		include($wire->config->paths->root.'zenphoto/zp-data/zenphoto.cfg.php');
		self::$zdb = new \PDO("mysql:dbname=$_zp_conf_vars[mysql_database];host=$_zp_conf_vars[mysql_host]", $_zp_conf_vars['mysql_user'], $_zp_conf_vars['mysql_pass']);
		return self::$zdb;
	}

	protected static function fetchAlbumImages($name) {
		$db = self::zenphotoDB();
		return $GLOBALS['wire']->cache->get("album-images--$name", $GLOBALS['wire']->config->debug ? WireCache::expireNow : WireCache::expireDaily, function() use ($db, $name) {
			$images = [];

			$sth = $db->prepare("SELECT `id` FROM `zp_albums` WHERE `folder`=?");
			$sth->execute([$name]);
			if (!($row = $sth->fetch(\PDO::FETCH_OBJ))) {
				site_error("Album with name '$name' does not exist.");
				return $images;
			}

			$sth = $db->query("SELECT `filename`,`width`,`height` FROM `zp_images` WHERE `albumid`=$row->id ORDER BY `sort_order` ASC");
			while ($img = $sth->fetch(\PDO::FETCH_OBJ)) {
				$img->width = intval($img->width);
				$img->height = intval($img->height);
				$images[] = $img;
			}

			return $images;
		});
	}

	protected static function render($template_name, $vars) {
		$vars['width'] = max(F\pluck($vars['images'], 'width'));
		$vars['height'] = max(F\pluck($vars['images'], 'height'));
		$vars['assets_url'] = $GLOBALS['wire']->config->urls->assets;
		$vars['album_url'] = "{$GLOBALS['wire']->config->urls->root}zenphoto/albums/$vars[name]/";
		$vars['poster'] = $vars['images'][0];
		$vars['id'] = str_replace('/', '--', $vars['name']);
		$vars['music'] = F\map(glob($GLOBALS['wire']->config->paths->assets."slideshows/$vars[name]/*.mp3"), function($s) { return basename($s, '.mp3'); });
		$has_custom_info = is_readable($GLOBALS['wire']->config->paths->assets."slideshows/$vars[name]/info.js");
		return $GLOBALS['twig']->render("components/$template_name.html", $vars);
	}

	public static function slideshow(ShortcodeInterface $s) {
		$name = $s->getParameter('name');
		$images = static::fetchAlbumImages($name);

		$vars = compact('name','images');
		return static::render('slideshow', $vars);
	}

	public static function motion(ShortcodeInterface $s) {
		$name = $s->getParameter('name');
		$title = ucwords(str_replace(['-','/'], ' ', $name));
		$js = str_replace([' ','/'], '', $title);
		$timing = $s->getParameter('timing', self::DEFAULT_MOTION_TIMING);
		$start = $s->getParameter('start', self::DEFAULT_MOTION_START);
		$autoplay = $s->getParameter('autoplay', false);
		$fade_duration = intval($s->getParameter('fade-duration'));
		$music_delay = $s->getParameter('music-delay', 0);
		$has_custom_info = is_readable($GLOBALS['wire']->config->paths->assets."slideshows/$name/info.js");
		$images = static::fetchAlbumImages($name);

		$vars = compact('name','images','title','js','timing','start','has_custom_info','autoplay','music_delay','fade_duration');
		return static::render('motion', $vars);
	}

	public static function video(ShortcodeInterface $s) {
		$name = $s->getParameter('name');
		$width = intval($s->getParameter('width'));
		$height = intval($s->getParameter('height'));

		$path = "{$GLOBALS['wire']->config->urls->assets}videos/$name/";
		$swf_path = "{$GLOBALS['wire']->config->urls->assets}media-element/build/flashmediaelement.swf";
		
		$vars = compact('name','width','height','path','swf_path');
		return $GLOBALS['twig']->render("components/video.html", $vars);
	}

}
